[phases.setup]
nixPkgs = ["php83", "nginx", "libmysqlclient", "php83Packages.composer"]

[phases.build]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx",
  "composer install --ignore-platform-reqs"
]

[start]
cmd = '''
php-fpm --nodaemonize --fpm-config /assets/php-fpm.conf --pid /tmp/php-fpm.pid --fpm-listen=/run/php-fpm.sock &
nginx -c /nginx.conf
'''
